Repository Gaepo-transcendance-fighters/FRONT-END, pull requests merged in 2023-09, with the labels that each got.

#117 113 qa login chat jeekim 1
  frontend/app/login/auth/page.tsx
  frontend/app/mypage/page.tsx
  frontend/app/page.tsx
  frontend/app/secondauth/page.tsx
  frontend/components/main/InviteGame/FriendGameButton.tsx
  frontend/components/main/InviteGame/MemberGameButton.tsx
  frontend/components/main/InviteGame/WaitAccept.tsx
  frontend/components/main/chat_window/BottomField/BottomField.tsx
  frontend/components/main/friend_list/Friend.tsx
  frontend/components/main/friend_list/FriendList.tsx
  frontend/components/main/friend_list/FriendProfile.tsx
  frontend/components/main/member_list/MemberModal.tsx
  frontend/components/main/myprofile/MyGameLog.tsx
  frontend/components/main/myprofile/MyProfile.tsx
  frontend/components/main/myprofile/SecondAuth.tsx
  frontend/components/public/Layout.tsx
  frontend/type/type.tsx
Labels: bug

#170 167 changing img in my profile modal
  frontend/app/login/auth/page.tsx
  frontend/app/mypage/page.tsx
  frontend/components/main/friend_list/BlockProfile.tsx
  frontend/components/main/friend_list/FriendProfile.tsx
  frontend/components/main/member_list/Member.tsx
  frontend/components/main/member_list/MemberModal.tsx
  frontend/components/public/Layout.tsx
  frontend/context/UserContext.tsx
  frontend/type/My.tsx
  frontend/type/type.tsx
Labels: bug

#176 [FIX] 상대 프로필에서 다른 사람의 닉네임이 뜬다.
  frontend/components/main/friend_list/FriendProfile.tsx
  frontend/components/main/member_list/MemberModal.tsx
Labels: bug

#183 171 rm nickname change in my profile
  frontend/app/mypage/page.tsx
  frontend/components/main/myprofile/MyGameLog.tsx
  frontend/components/main/myprofile/SecondAuth.tsx
  frontend/components/main/room_list/ProtectedModal.tsx
  frontend/type/GameType.tsx
  frontend/type/My.tsx
Labels: feature

#184 [FIX] show unproper nickname at gamelog
  frontend/components/main/friend_list/FriendGameLog.tsx
  frontend/components/main/member_list/MemberGameLog.tsx
Labels: bug

#188 [FEAT] implement prevent duplicate login
  frontend/app/home/page.tsx
Labels: feature

#186 185 member modal rankpoint
  frontend/components/main/chat_window/ChatField/DmChat.tsx
  frontend/components/main/friend_list/FriendGameLog.tsx
  frontend/components/main/friend_list/FriendList.tsx
  frontend/components/main/friend_list/FriendProfile.tsx
  frontend/components/main/member_list/Member.tsx
  frontend/components/main/member_list/MemberGameLog.tsx
  frontend/components/main/member_list/MemberModal.tsx
  frontend/components/main/myprofile/MyGameLog.tsx
  frontend/components/main/myprofile/MyProfile.tsx
  frontend/components/public/Layout.tsx
  frontend/external_functions/RoomEnter.tsx
  frontend/hooks/useRequireAuth.ts
  frontend/type/GameType.tsx
Labels: bug

#190 로컬스토리지에 암호화 기법 적용
  .gitignore
  README.md
  frontend/app/game/friend/optionselect/page.tsx
  frontend/app/game/page.tsx
  frontend/app/gameplaying/page.tsx
  frontend/app/home/page.tsx
  frontend/app/init/page.tsx
  frontend/app/inwaiting/page.tsx
  frontend/app/login/auth/page.tsx
  frontend/app/optionselect/page.tsx
  frontend/app/page.tsx
  frontend/components/game/ingame/PingPong.tsx
  frontend/components/game/ingame/WaterBomb.tsx
  frontend/components/main/InviteGame/FriendGameButton.tsx
  frontend/components/main/InviteGame/InviteGame.tsx
  frontend/components/main/InviteGame/MemberGameButton.tsx
  frontend/components/main/friend_list/FriendGameLog.tsx
  frontend/components/main/member_list/MemberGameLog.tsx
  frontend/components/main/myprofile/MyGameLog.tsx
  frontend/components/public/ModalPortal.tsx
  frontend/context/AuthContext.tsx
  frontend/external_functions/RoomEnter.tsx
  frontend/hooks/useRequireAuth.ts
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#193 FIX: set-nickname add
  frontend/app/init/page.tsx
Labels: bug, enhancement

#198 친선전에서 option select 페이지로
  frontend/app/home/page.tsx
  frontend/components/main/InviteGame/InviteGame.tsx
  frontend/components/main/chat_window/RoomTitleField/RoomTitleField.tsx
Labels: bug

#200 [FIX] /home 으로 바로 접속했을때 이미지와 닉네임이 받아와지지 않는 버그
  frontend/components/public/Layout.tsx
Labels: bug

#204 랭크전 활성 및 게임 결과 페이지 완성
  frontend/app/game/friend/optionselect/page.tsx
  frontend/app/game/page.tsx
  frontend/app/gameplaying/page.tsx
  frontend/app/gameresult/page.tsx
  frontend/app/home/page.tsx
  frontend/app/inwaiting/page.tsx
  frontend/components/game/GameStartButton.tsx
  frontend/components/game/ingame/WaterBomb.tsx
  frontend/type/GameType.tsx
Labels: enhancement, feature

#206 [FIX] 마이페이지 이메일 보이지 않던 에러 수정 && 로그인 로직 개편 (새로고침 폐기)
  frontend/app/home/page.tsx
  frontend/app/login/auth/page.tsx
  frontend/app/mypage/page.tsx
  frontend/app/page.tsx
  frontend/hooks/useRequireAuth.ts
Labels: bug, enhancement

#210 [FEAT] : if clicking GameStartButton, i go out from the room i was in
  frontend/components/game/GameStartButton.tsx
  frontend/components/main/room_list/CreateRoomModal.tsx
  frontend/external_functions/RoomEnter.tsx
Labels: feature

#216 [FEAT] : 2차인증 에러 수정완료.
  frontend/app/mypage/page.tsx
  frontend/app/secondauth/page.tsx
Labels: bug

#219 [FIX] secondauth 페이지 주소를 직접 입력해서 방문하는 경우 막아져 있지 않다.
  frontend/hooks/useRequireAuth.ts
Labels: bug

#227 [FIX] set userState nickname at init
  frontend/app/init/page.tsx
Labels: bug

#231 [FIX] move to login when signin
  frontend/app/home/page.tsx
  frontend/app/login/auth/page.tsx
Labels: bug

#225 isonline에 게임 상태 추가
  frontend/app/gameresult/page.tsx
  frontend/app/home/page.tsx
  frontend/app/optionselect/page.tsx
  frontend/app/page.tsx
  frontend/components/game/GameStartButton.tsx
  frontend/components/main/InviteGame/FriendGameButton.tsx
  frontend/components/main/InviteGame/InviteGame.tsx
  frontend/components/main/InviteGame/MemberGameButton.tsx
  frontend/components/main/friend_list/Friend.tsx
  frontend/components/main/friend_list/FriendProfile.tsx
  frontend/components/public/Modals.tsx
  frontend/context/ModalContext.tsx
  frontend/type/type.tsx
Labels: feature

#236 234 should be unset
  frontend/components/main/member_list/Member.tsx
  frontend/components/main/room_list/Room.tsx
Labels: bug

#242 Mem profile closes when mem goes out
  frontend/components/main/member_list/MemberModal.tsx
Labels: bug

#196 [FEAT] 중복 접속을 막기위한 마지막 설정 (마지막단계에서만 머지해주세요)
  frontend/app/home/page.tsx
Labels: enhancement

#252 [FEAT] : closes room and empties room when friend game
  frontend/app/home/page.tsx
Labels: feature

#256 [FIX] : fixed BottomField's auto focus problem
  frontend/components/main/chat_window/BottomField/BottomField.tsx
Labels: bug

#257 [FEAT] : if I'm admin and target is admin, then right click is banned
  frontend/components/main/member_list/Member.tsx
Labels: feature
